apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: http-ace-flow-ci-binding
  namespace: cp4i-2
spec:
  params:
    - name: repo-url
      value: $(body.repository.clone_url)

    - name: revision
      value: $(body.ref)
